### ISSUE TITLE
Error on "Set Cursor word"

### ISSUE THREAD

**Issue by averrin** [t9md/atom-lazy-motion#14]
/home/alexeynabrodov/.atom/packages/lazy-motion/lib/ui.coffee:48
Hide Stack Trace
ReferenceError: emitCommand is not defined
    at atom-text-editor.subscriptions.add.atom.commands.add.lazy-motion:set-cursor-word (/home/alexeynabrodov/.atom/packages/lazy-motion/lib/ui.coffee:48:41)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:259:29)
    at /usr/share/atom-beta/resources/app.asar/src/command-registry.js:3:59
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom-beta/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:210:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom-beta/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom-beta/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:259:29)
    at /usr/share/atom-beta/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:3:59)

**Comment by t9md** [comment]
released v0.5.1.
