### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by filipesabella** [t9md/atom-lazy-motion#2]
Not sure how to reproduce unfortunately, the plugin got to an invalid state where I can't close the bottom view anymore and then this error is thrown.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [lazy-motion](https://github.com/t9md/atom-lazy-motion) package, v0.1.5
### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
At /Users/filipe/.atom/packages/lazy-motion/lib/main.coffee:112

TypeError: Cannot read property 'start' of undefined
  at Object.module.exports.land (/Users/filipe/.atom/packages/lazy-motion/lib/main.coffee:112:58)
  at lazy-motion-ui.UI.confirm (/Users/filipe/.atom/packages/lazy-motion/lib/ui.coffee:64:11)
  at atom-text-editor.subscriptions.add.atom.commands.add.core:confirm (/Users/filipe/.atom/packages/lazy-motion/lib/ui.coffee:26:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:16.1.0 editor:consolidate-selections (atom-text-editor.editor.lazy-motion.mini.is-focused)
     -0:16.1.0 core:cancel (atom-text-editor.editor.lazy-motion.mini.is-focused)
  2x -0:16.1.0 blur (atom-text-editor.editor.lazy-motion.mini.is-focused)
     -0:16 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:15.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:15.6.0 lazy-motion:forward (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:15.6.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:14.6.0 core:confirm (atom-text-editor.editor.lazy-motion.mini.is-focused)
  2x -0:14.6.0 blur (atom-text-editor.editor.lazy-motion.mini.is-focused)
     -0:11.9.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:11.7.0 lazy-motion:forward (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:11.7.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:06.6.0 editor:move-to-first-character-of-line (atom-text-editor.editor.lazy-motion.mini.is-focused)
     -0:06.3.0 core:select-right (atom-text-editor.editor.lazy-motion.mini.is-focused)
  2x -0:03.7.0 core:backspace (atom-text-editor.editor.lazy-motion.mini.is-focused)
     -0:01.2.0 core:confirm (atom-text-editor.editor.lazy-motion.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "linter-scalac",
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "ignoredNames": [
      "node_modules"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.7
cursor-history, v0.4.14
highlight-selected, v0.10.1
language-clojure, v0.16.0
language-crystal-actual, v0.28.0
language-haml, v0.21.0
language-haskell, v1.1.8
lazy-motion, v0.1.5
linter, v1.2.3
markdown-writer, v1.6.0
vim-mode, v0.55.0

# Dev
No dev packages
```

**Comment by t9md** [comment]
Sorry for that, I could reproduce it. will fix soon.

**Comment by filipesabella** [comment]
thanks!

**Comment by t9md** [comment]
you're welcome!

**Comment by lmartins** [comment]
Seen this error today, which pointed me here. 
Im running the latest version. Is there any more info I can provide?

**Comment by t9md** [comment]
Really... This is another issue maybe, I want you to provide procedure to reproduce.

**Comment by t9md** [comment]
and what happened after the issue. Did you need to restart atom or was able to continue using Atom and lazy-motion itself?

**Comment by lmartins** [comment]
it became impossible to dismiss the search input, and it would trigger a new error message each time i've pressed the shortcut to activate the plugin.

**Comment by t9md** [comment]
Oh, sorry for that.
If next time you face this situation I want to know
- Error stack trace
- Operation you did at that time

And also I want your keymap to got hint what possible operation you did.
For myself I couldn't reproduce this isssue except first reported one.
